// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class AlteraImovelValidoTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void alteraImovelValido() {
    driver.Navigate().GoToUrl("https://localhost:3001/");
    driver.Manage().Window.Size = new System.Drawing.Size(839, 1050);
    driver.FindElement(By.LinkText("Entrar ou Cadastrar")).Click();
    driver.FindElement(By.LinkText("Meus Imoveis")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(1) .far")).Click();
    driver.FindElement(By.Id("wrapper")).Click();
    driver.FindElement(By.Id("ValorDoAluguel")).SendKeys("350");
    driver.FindElement(By.Id("ValorDoAluguel")).SendKeys(Keys.Enter);
  }
}
