// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class AlterarPessoaVlidaTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), new ChromeOptions().ToCapabilities());
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void alterarPessoaVlida() {
    driver.Navigate().GoToUrl("https://localhost:44368/");
    driver.Manage().Window.Size = new System.Drawing.Size(1616, 876);
    driver.FindElement(By.LinkText("Entrar ou Cadastrar")).Click();
    driver.FindElement(By.LinkText("Minha Conta")).Click();
    driver.FindElement(By.CssSelector(".far")).Click();
    driver.FindElement(By.Id("Cep")).Click();
    driver.FindElement(By.Id("Cep")).SendKeys("345000");
    driver.FindElement(By.Id("DataNascimento")).Click();
    driver.FindElement(By.Id("DataNascimento")).SendKeys("0001-03-01");
    driver.FindElement(By.Id("DataNascimento")).SendKeys("0019-03-01");
    driver.FindElement(By.Id("DataNascimento")).SendKeys("0199-03-01");
    driver.FindElement(By.Id("DataNascimento")).SendKeys("1997-03-01");
    driver.FindElement(By.CssSelector(".form-group > .btn")).Click();
  }
}
