// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class InserirPessoaVlidaTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new RemoteWebDriver(new Uri("http://localhost:4444/wd/hub"), new ChromeOptions().ToCapabilities());
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void inserirPessoaVlida() {
    driver.Navigate().GoToUrl("https://localhost:44368/");
    driver.Manage().Window.Size = new System.Drawing.Size(1616, 876);
    driver.FindElement(By.LinkText("Entrar ou Cadastrar")).Click();
    driver.FindElement(By.LinkText("Minha Conta")).Click();
    driver.FindElement(By.LinkText("Cadastrar")).Click();
    driver.FindElement(By.Id("CodigoPessoa")).Click();
    driver.FindElement(By.Id("CodigoPessoa")).SendKeys("1");
    driver.FindElement(By.Id("TipoPessoa")).Click();
    driver.FindElement(By.Id("TipoPessoa")).Click();
    driver.FindElement(By.Id("Nome")).Click();
    driver.FindElement(By.Id("Nome")).SendKeys("Maycon Douglas");
    driver.FindElement(By.Id("Email")).Click();
    driver.FindElement(By.Id("Email")).SendKeys("maycon@hotmail.com");
    driver.FindElement(By.Id("Telefone")).Click();
    driver.FindElement(By.Id("Telefone")).SendKeys("9999999999");
    driver.FindElement(By.Id("Cpf")).Click();
    driver.FindElement(By.Id("Cpf")).SendKeys("88888888888");
    driver.FindElement(By.Id("Sexo")).Click();
    driver.FindElement(By.Id("Sexo")).Click();
    driver.FindElement(By.Id("DataNascimento")).Click();
    driver.FindElement(By.Id("DataNascimento")).SendKeys("0001-03-01");
    driver.FindElement(By.Id("DataNascimento")).SendKeys("0019-03-01");
    driver.FindElement(By.Id("DataNascimento")).SendKeys("0199-03-01");
    driver.FindElement(By.Id("DataNascimento")).SendKeys("1997-03-01");
    driver.FindElement(By.Id("Rg")).Click();
    driver.FindElement(By.Id("Rg")).SendKeys("9999887655");
    driver.FindElement(By.Id("Cep")).Click();
    driver.FindElement(By.Id("Cep")).SendKeys("789566666");
    driver.FindElement(By.Id("Rua")).Click();
    driver.FindElement(By.Id("Rua")).SendKeys("rua A");
    driver.FindElement(By.Id("NumeroDoEndereco")).Click();
    driver.FindElement(By.Id("NumeroDoEndereco")).SendKeys("23");
    driver.FindElement(By.Id("EstadoUf")).Click();
    driver.FindElement(By.Id("EstadoUf")).SendKeys("SE");
    driver.FindElement(By.Id("Cidade")).Click();
    driver.FindElement(By.Id("Cidade")).SendKeys("Itabaiana");
    driver.FindElement(By.Id("Bairro")).Click();
    driver.FindElement(By.Id("Bairro")).SendKeys("Centro");
    driver.FindElement(By.CssSelector(".form-group > .btn")).Click();
  }
}
